### ISSUE TITLE
Cannot create new cf.EventDispatcher() when loading with ES6 Module Bundler

### ISSUE THREAD

**Issue by jorditarrida** [space10-community/conversational-form#218]
Hi,
I am trying to replicate the [voice examples](https://space10-community.github.io/conversational-form/docs/0.9.71/functionality/voice/) on your website. I am loading `conversational-form` using Webpack on my project with `import cf from 'conversational-form'`. When I try to instantiate a `new cf.EventDispatcher()` I get the following error `__WEBPACK_IMPORTED_MODULE_0_conversational_form___default.a.EventDispatcher is not a constructor`. I'm kind of a newbie in using Webpack as a module bundler so I might be missing some steps, but I'd say the error occurs because the EventDispatcher class is not exported and thus not importable with Webpack.
Thanks in advance for your help :)
Jordi

**Comment by jenssogaard** [comment]
Hi @jorditarrida. I'm not exactly sure if you hit a bug or what the problem might be. Let me have a look in the coming days and report back.

**Comment by jenssogaard** [comment]
@jorditarrida did you ever figure this out?

**Comment by jorditarrida** [comment]
@jenssogaard nope, if you could check on it that'd be great :)

**Comment by jenssogaard** [comment]
@jorditarrida alright, I'll have a look.

**Comment by tonyyb** [comment]
I've got the same issue !

**Comment by jenssogaard** [comment]
@jorditarrida @tonyyb I experience the same issue. I'll try to debug and figure out what is wrong.

**Comment by Rchanger** [comment]
I've got the same issue ,any updates on it

**Comment by jenssogaard** [comment]
@Rchanger no solution yet. I'm still trying to figure it out.

**Comment by will3** [comment]
problem is,
export function exports cf.ConversationalForm, not cf

**Comment by jenssogaard** [comment]
@will3 indeed, that is the issue. 

@Rchanger @tonyyb  @jorditarrida so the issue is that if I change the export to just cf then existing declarations breaks:
Before:
`var myCF = new cf.startTheConversation({})`
After:
`var myCF = new cf.ConversationalForm.startTheConversation({})`

So for the sake of SemVer I see no other option than to wait for a v1.0 release as it is a breaking change. Any other suggestions on how to go about it will be warmly received.

**Comment by diedea** [comment]
any update on this?
Running into the same problem when using meteor - using [this](https://github.com/space10-community/conversational-form/issues/151) fix removed the EventDispatcher error for me, however while the form is created, I cannot modify it with any of the functions (options in startTheConversation are not applied, no event listener added...)

**Comment by diedea** [comment]
I now loaded from the external script and I get the form version and options printed to the console, as well as seeing/being able to use the dialogue. However, none of my options (e.g. robot picture) are applied, and I still get the `cf.EventDispatcher is not a constructor` error.

**Comment by jenssogaard** [comment]
@diedea the solution should be clear - fixing the export as described above. However, it must be in a 1.0 beacuse of SemVer. I'll try to get a 1.0 out very soon.

Regarding Meteor - any chance you could put together a very simple example repo for me to look at?

**Comment by diedea** [comment]
Thanks for your help @jenssogaard - I published a small exemplatory repo [here](https://github.com/diedea/conv_bot). A real beginner here, so I feel I don't have a lot of insight.

**Comment by rafafotes** [comment]
Any workaround to solve this while 1.0 isn't out.

**Comment by jenssogaard** [comment]
@rafafotes, unfortunately, you will have to wait until 1.0 is released which will hopefully happen sometime next month.

**Comment by edlgg** [comment]
Has this been solved? Im still getting the same error 'cf.EventDispatcher is not a constructor' im using nuxt.js in case it has any relevance.

**Comment by jenssogaard** [comment]
Hi @edlgg. We have had a bit of a delay on rolling out v1.0.0 where this issue is fixed. I hope it will be released in the next 4 weeks. I'm sorry for the delay.

**Comment by edlgg** [comment]
No worries I! I managed to do what I was trying to do anyways. Thank you for developing this project. It is very useful.

**Comment by rahulrawat1210** [comment]
When will v1.0.0 be released? Still getting the error EventDispatcher is not a constructor

**Comment by jenssogaard** [comment]
@rahulrawat1210 I hope it will be released within 2-3 weeks.
